'use client';import {FormEvent,useState} from 'react';
type Props={baseUrl:string};
export default function AdminManager({baseUrl}:Props){const [notice,setNotice]=useState('');const [busy,setBusy]=useState('');async function create(kind:string,e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(kind);setNotice('');const fd=new FormData(e.currentTarget);const data=Object.fromEntries(fd.entries());if(data.approvalRequired)data.approvalRequired=true;const res=await fetch(`/api/admin/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await res.json();setBusy('');if(!res.ok){setNotice(body.error||'Could not create item.');return}const path=kind==='campaigns'?`/register/campaign/${body.item.code}`:kind==='allocations'?`/register/organisation/${body.item.code}`:`/register/speaker/${body.item.code}`;setNotice(`Created successfully: ${baseUrl}${path}`);e.currentTarget.reset()}
 return <div className="admin-tools">
  {notice&&<div className="admin-notice">{notice}</div>}
  <section className="admin-tool"><p className="eyebrow dark">Campaign Invitation</p><h2>Create a campaign</h2><p>Use for targeted campaigns such as “Final 50 Places”.</p><form onSubmit={e=>create('campaigns',e)}><input name="name" placeholder="Campaign name" required/><select name="event" defaultValue="expo-2026"><option value="expo-2026">Banking CEE Expo 2026</option><option value="summit-2027">Digital Banking CEE Summit 2027</option></select><select name="participantType" defaultValue="delegate"><option value="delegate">Delegate</option><option value="speaker">Speaker</option></select><input name="capacity" type="number" min="1" placeholder="Capacity" required/><input name="expiresAt" type="datetime-local"/><label className="admin-check"><input name="approvalRequired" type="checkbox"/> Approval required before registration</label><button disabled={busy==='campaigns'}>{busy==='campaigns'?'CREATING…':'CREATE CAMPAIGN →'}</button></form></section>
  <section className="admin-tool"><p className="eyebrow dark">Organisation Allocation</p><h2>Create an allocation</h2><p>Use for sponsor representatives, association allocations or approved teams.</p><form onSubmit={e=>create('allocations',e)}><input name="organisation" placeholder="Organisation" required/><input name="name" placeholder="Internal allocation name (optional)"/><select name="event" defaultValue="expo-2026"><option value="expo-2026">Banking CEE Expo 2026</option><option value="summit-2027">Digital Banking CEE Summit 2027</option></select><select name="participantType" defaultValue="sponsor"><option value="sponsor">Sponsor Representative</option><option value="delegate">Delegate</option><option value="association">Association</option><option value="media">Media</option></select><input name="capacity" type="number" min="1" placeholder="Number of registrations" required/><input name="expiresAt" type="datetime-local"/><button disabled={busy==='allocations'}>{busy==='allocations'?'CREATING…':'CREATE ALLOCATION →'}</button></form></section>
  <section className="admin-tool"><p className="eyebrow dark">Speaker Invitation</p><h2>Create a speaker invite</h2><p>Use for a named speaker or an organisation nomination. Leave the person fields empty when the final speaker is not yet known.</p><form onSubmit={e=>create('speaker-invites',e)}><select name="event" defaultValue="expo-2026"><option value="expo-2026">Banking CEE Expo 2026</option><option value="summit-2027">Digital Banking CEE Summit 2027</option></select><input name="organisation" placeholder="Organisation (optional)"/><input name="personName" placeholder="Speaker name (optional)"/><input name="email" type="email" placeholder="Speaker email (optional)"/><input name="expiresAt" type="datetime-local"/><button disabled={busy==='speaker-invites'}>{busy==='speaker-invites'?'CREATING…':'CREATE SPEAKER INVITE →'}</button></form></section>
 </div>}
