'use client';
import { FormEvent, useState } from 'react';
const interests=['AI & Automation','Digital Transformation','Payments','Lending','Customer Experience','Open Banking / Open Finance','Cybersecurity','Fraud Prevention','Risk & Compliance','Digital Identity','Core Banking','Cloud','Data & Analytics'];
const meetingTypes=['Banks & Financial Institutions','Technology & Solution Providers','Regulators & Associations','All Relevant Participants'];
type Props={mode:'token'|'campaign'|'speaker'|'speaker-invite'|'allocation'; tokenOrCode:string; event:string; initial?:Record<string,string>; campaignName?:string};
export default function RegistrationForm({mode,tokenOrCode,event,initial={},campaignName}:Props){
 const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const [data,setData]=useState<any>({...initial,interests:[],networking:false,meetingTypes:[],discussionTopics:[],marketing:false,bio:''});
 const set=(k:string,v:any)=>setData((d:any)=>({...d,[k]:v})); const toggle=(k:string,v:string)=>set(k,data[k]?.includes(v)?data[k].filter((x:string)=>x!==v):[...(data[k]||[]),v]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const res=await fetch('/api/registration/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,tokenOrCode,event,...data})});const body=await res.json();setBusy(false);if(!res.ok){setError(body.error||'Registration could not be completed.');return}setDone(true)}
 if(done)return <div className="registration-confirmed"><p className="eyebrow dark">Registration Confirmed</p><h2>We Look Forward to Welcoming You.</h2><p>A confirmation has been sent to <strong>{data.email}</strong>.</p><div className="actions"><a className="btn registration-dark-btn" href={event==='expo-2026'?'/expo':'/summit'}>EXPLORE THE EVENT →</a></div></div>;
 return <form className="registration-form" onSubmit={submit}>
  <div className="registration-progress"><span className={step===1?'active':''}>01 Details</span><span className={step===2?'active':''}>02 Interests</span><span className={step===3?'active':''}>03 Networking</span><span className={step===4?'active':''}>04 Review</span></div>
  {campaignName&&<div className="campaign-note"><strong>{campaignName}</strong><span>Controlled campaign registration</span></div>}
  {step===1&&<div className="registration-fields"><h3>{mode==='speaker'||mode==='speaker-invite'?'Speaker Details':'Professional Details'}</h3>{[['firstName','First Name *'],['lastName','Last Name *'],['jobTitle','Job Title *'],['organisation','Company / Organisation *'],['email','Business Email *'],['mobile','Mobile Number'],['country','Country *'],['linkedin','LinkedIn Profile']].map(([k,l])=><label key={k}><span>{l}</span><input required={l.includes('*')} type={k==='email'?'email':'text'} value={data[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}{(mode==='speaker'||mode==='speaker-invite')&&<label className="form-wide"><span>Short Professional Bio *</span><textarea required rows={5} value={data.bio||''} onChange={e=>set('bio',e.target.value)}/></label>}</div>}
  {step===2&&<div><h3>Professional Interests</h3><p className="form-help">Select the areas most relevant to your work and the conversations you want to follow.</p><div className="choice-grid">{interests.map(x=><button type="button" key={x} className={data.interests.includes(x)?'selected':''} onClick={()=>toggle('interests',x)}>{x}</button>)}</div></div>}
  {step===3&&<div><h3>Networking</h3><label className="network-toggle"><input type="checkbox" checked={data.networking} onChange={e=>set('networking',e.target.checked)}/><span>I would like to participate in networking & 1:1 meetings.</span></label>{data.networking&&<><p className="form-help">Who are you most interested in meeting?</p><div className="choice-grid compact">{meetingTypes.map(x=><button type="button" key={x} className={data.meetingTypes.includes(x)?'selected':''} onClick={()=>toggle('meetingTypes',x)}>{x}</button>)}</div><p className="form-help">Topics you'd like to discuss</p><div className="choice-grid">{interests.map(x=><button type="button" key={x} className={data.discussionTopics.includes(x)?'selected':''} onClick={()=>toggle('discussionTopics',x)}>{x}</button>)}</div></>}<label className="network-toggle marketing"><input type="checkbox" checked={data.marketing} onChange={e=>set('marketing',e.target.checked)}/><span>I'd like to receive updates about future Banking CEE events, Insights and community activities.</span></label></div>}
  {step===4&&<div className="review-card"><h3>Review Your Registration</h3><dl><div><dt>Name</dt><dd>{data.firstName} {data.lastName}</dd></div><div><dt>Position</dt><dd>{data.jobTitle}</dd></div><div><dt>Organisation</dt><dd>{data.organisation}</dd></div><div><dt>Email</dt><dd>{data.email}</dd></div><div><dt>Networking</dt><dd>{data.networking?'Yes':'No'}</dd></div></dl><label className="network-toggle"><input required type="checkbox"/><span>I have read and agree to the Event Participation Terms and acknowledge the Privacy Policy.</span></label></div>}
  {error&&<p className="form-error">{error}</p>}<div className="registration-nav">{step>1&&<button type="button" className="back" onClick={()=>setStep(step-1)}>← BACK</button>}{step<4?<button type="button" onClick={()=>setStep(step+1)}>CONTINUE →</button>:<button disabled={busy} type="submit">{busy?'CONFIRMING…':'CONFIRM REGISTRATION →'}</button>}</div>
 </form>
}
