import Image from 'next/image';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import PartnerLogoGrid from '../../components/PartnerLogoGrid';

const associations=['44.png','46.png','47.png','48.png','49.png','51.png','52.png','53.png'];
export default function Partners(){return <main className="inner-page partners-page">
  <section className="partner-hero">
    <Header ctaLabel="Explore Partnerships" activePage="partners" ctaHref="#partnership-options"/>
    <div className="shell partner-hero-content"><p className="eyebrow">Partner With Banking CEE</p><h1>Build Meaningful Relationships With Banking Leaders Across CEE.</h1><p>Connect your organisation with senior banking decision-makers through flagship events, tailored experiences and year-round opportunities designed around meaningful industry engagement.</p><a className="btn btn-primary" href="#partnership-options">Explore Partnership Opportunities ↓</a><div className="partner-hero-line">FLAGSHIP EVENTS · TAILORED EVENTS · WEBINARS</div></div></section>

  <section className="section-white"><div className="shell"><div className="partner-intro"><div><p className="eyebrow dark">Participation by Design</p><h2>Bringing the Right People Together.</h2></div><p>Banking CEE brings together banking leaders and technology partners from across Central &amp; Eastern Europe through a carefully structured participation model that encourages relevant conversations, knowledge exchange and long-term relationships.</p></div>
  <div className="partner-ratio"><div className="partner-ratio-main"><strong>~70%</strong><span>Banks, Financial Institutions, Regulators &amp; Banking Associations</span><small>COMPLIMENTARY · QUALIFICATION-BASED</small></div><div className="partner-ratio-side"><strong>~30%</strong><span>Technology &amp; Solution Providers</span><small>SPONSORSHIP-BASED PARTICIPATION</small></div></div>
  <div className="partner-proof-stats"><div><strong>15+</strong><span>Events</span></div><div><strong>20+</strong><span>CEE Countries</span></div><div><strong>2,500+</strong><span>Attendees</span></div><div><strong>100+</strong><span>Technology Partners</span></div></div>
  <div className="trusted-partners"><p className="eyebrow dark">Trusted by Technology Partners Across CEE</p><PartnerLogoGrid/></div></div></section>

  <section className="section-light"><div className="shell"><p className="eyebrow dark">Two Events. Two Distinct Experiences.</p><h2>Choose the Environment That Fits Your Objectives.</h2><p className="section-intro-copy">Banking CEE offers two established event formats, each creating a different environment for technology partners to engage with banking decision-makers from across the region.</p><div className="partner-event-grid"><article className="partner-event expo-partner-event"><Image src="/images/expo-2025-tietoevry-activation.jpg" alt="Banking CEE Expo partner activation" fill className="cover"/><div className="partner-event-shade"/><div className="partner-event-copy"><span>Banking CEE Expo 2026 · Scale &amp; Regional Reach</span><h3>250+ Attendees · 20+ CEE Countries · 50+ Speakers · 3 Stages</h3><p>Thought Leadership · Exhibition · Brand Visibility · 1:1 Meetings · Networking &amp; Hospitality</p><a href="/expo#partners">Explore Expo Sponsorship →</a></div></article><article className="partner-event summit-partner-event"><Image src="/images/summit-2026-partner.jpg" alt="Digital Banking CEE Summit partner experience" fill className="cover"/><div className="partner-event-shade"/><div className="partner-event-copy"><span>Digital Banking CEE Summit 2027 · Focus &amp; Seniority</span><h3>100+ Attendees · 75%+ C-Level, Directors &amp; Heads · 30+ Speakers · 1 Stage</h3><p>Thought Leadership · Brand Visibility · 1:1 Meetings · Networking · Cocktail Reception</p><a href="/summit#partners">Explore Summit Sponsorship →</a></div></article></div></div></section>

  <section className="section-white" id="partnership-options"><div className="shell"><p className="eyebrow dark">Beyond Our Flagship Events</p><h2>Different Formats for Different Objectives.</h2><p className="section-intro-copy">Banking CEE partnerships extend beyond our flagship events, creating opportunities for more targeted engagement with the regional banking community.</p><div className="partner-format-list">
   <article><div className="partner-format-copy"><span>01 — FLAGSHIP EVENTS</span><h3>Banking CEE Expo &amp; Digital Banking CEE Summit</h3><ul><li>100–300 senior decision-makers</li><li>Thought leadership and speaking opportunities</li><li>Exhibition and brand visibility</li><li>1:1 meetings and networking</li><li>Regional engagement across the Banking CEE community</li></ul><p><strong>Great for:</strong> organisations looking for broader visibility, thought leadership and access to banking decision-makers across CEE.</p><a href="#flagship">Explore Flagship Events →</a></div><div className="partner-format-image"><Image src="/images/expo-2025-evrotrust-activation.jpg" alt="Flagship event partnership" fill className="cover"/></div></article>
   <article><div className="partner-format-copy"><span>02 — TAILORED EVENTS</span><h3>Your Audience. Your Topic. Your Event.</h3><ul><li>20–30 pre-qualified industry attendees</li><li>Premium dinner or roundtable formats</li><li>Dedicated topic and audience</li><li>Direct engagement in a focused environment</li></ul><p><strong>Great for:</strong> organisations looking for high-touch engagement with selected decision-makers around a specific topic, market or business objective.</p><a href="/contact?interest=sponsorship">Explore Tailored Events →</a></div><div className="partner-format-image"><Image src="/images/summit-2026-one-to-one.jpg" alt="Tailored Banking CEE event" fill className="cover"/></div></article>
   <article><div className="partner-format-copy"><span>03 — WEBINARS</span><h3>Take the Conversation Online.</h3><ul><li>Targeted topic and audience</li><li>Banking and industry perspectives</li><li>Interactive online discussion</li><li>Regional reach beyond physical events</li></ul><p><strong>Great for:</strong> organisations looking to showcase expertise, introduce new ideas or build thought leadership around a specific banking topic.</p><a href="/contact?interest=sponsorship">Explore Webinars →</a></div><div className="partner-format-image"><Image src="/images/summit-2026-keynote.jpg" alt="Banking CEE thought leadership" fill className="cover"/></div></article>
  </div></div></section>

  <section className="section-light"><div className="shell"><p className="eyebrow dark">Across the Banking CEE Community</p><h2>Other Ways to Work With Us.</h2><p className="section-intro-copy">Alongside sponsorship, Banking CEE works with selected organisations that help strengthen industry connections, support knowledge exchange and extend relevant conversations across Central &amp; Eastern Europe.</p><div className="association-strip">{associations.map(x=><div key={x}>
    <Image src={`/images/logos/associations/${x}`} alt="Banking association" fill/>
    </div>)}</div><div className="other-partner-actions"><a href="/contact?interest=association">Banking Association Partnership →</a><a href="/contact?interest=association">Media Partnership →</a></div></div></section>

  <section className="section-navy"><div className="shell simple-cta"><div><p className="eyebrow">Let&apos;s Work Together</p><h2>Find the Right Partnership for Your Objectives.</h2><p>Whether you&apos;re exploring one of our flagship events, a tailored event, webinar, association collaboration or media partnership, we&apos;d be happy to discuss the opportunity that best fits your objectives.</p></div><a className="btn btn-primary" href="/contact?interest=sponsorship">Get in Touch →</a></div></section>
  <Footer/>
</main>}
